### ISSUE TITLE
Adapt main view tabs font

### ISSUE THREAD

**Issue by HaLenB** [mobapi/dugout#12]

**Comment by fluciotto** [comment]
I don't understand what you mean. Could you explain a bit ?

**Comment by HaLenB** [comment]
Nvm, the tabs font (cf. screenshot attached) weren't visually according with the whole graphic chart of dugout but it seems that the v2 release corrected it

Gauffres gauffres gauffres

**Comment by fluciotto** [comment]
OK so could i close this issue ?

waffles waffles waffles
