### ISSUE TITLE
Labels missing when opening for the first time, without selecting a language

### ISSUE THREAD

**Issue by steve-rodrigue** [mobapi/dugout#18]
It seems like there is no default language.  If you delete your saved localStorage files and iopen the application, you will see a lot of [MISSING] labels.

As soon as you select a language, close the application and re-open it, the labels works, in the right language.

This issue occured on [v2.0.4](https://github.com/mobapi/dugout/releases/tag/v2.0.4)

**Comment by fluciotto** [comment]
These "[MISSING]" labels are gettext debug helpers.
Fixed in commit 8b1bb404de5f642438c8671b831151d69dd959d7
